title: Qian Dong
url: "https://github.com"
baseurl: "/DQ0408"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/DQ0408"
footer_text: "My Github"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/DQ0408/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
